version: 2.1
jobs:
  kics:
    docker:
      - image: checkmarx/kics:latest-alpine
    steps:
      - checkout
      - run:
          name: Run KICS
          command: |
            pwd
            ls -la
            /app/bin/kics scan -p ${PWD} -q /app/bin/assets -o results.json --ci
      - store_test_results:
          path: ~/results.json
      - store_artifacts:
          path: ~/results.json

workflows:
  version: 2
  build:
    jobs:
      - kics