version: 2.1
jobs:
  kics:
    docker:
      - image: checkmarx/kics:latest-alpine
    steps:
      - run: |
          mkdir -p /opt/workspace
          cd /opt/workspace
      - checkout
      - run:
          name: Run KICS
          command: |
            /app/bin/kics scan -p ${PWD} -q /app/bin/assets -o results.json --ci
      - store_test_results:
          path: /opt/workspace/results.json
      - store_artifacts:
          path: /opt/workspace/results.json

workflows:
  version: 2
  build:
    jobs:
      - kics