version: 2.1
jobs:
  kics:
    docker:
      - image: Checkmarx/kics:latest-alpien
    steps:
      - run: |
          mkdir -p /opt/workspace
          cd /opt/workspace
      - checkout
      - run:
          name: Run KICS
          command: |
            /app/bin/kics scan -p ${PWD} -q /app/bin/assets --ci

workflows:
  version: 2
  build:
    jobs:
      - kics